-- =====================================================================
-- 99 - Cleanup. Removes every object created by this demo.
-- DO NOT run until you are finished with the demo.
-- =====================================================================
USE ROLE ACCOUNTADMIN;

DROP AGENT IF EXISTS FPA_DEMO.FPA.FPA_AGENT;
DROP CORTEX SEARCH SERVICE IF EXISTS FPA_DEMO.FPA.FPA_ASSUMPTIONS_SEARCH;
DROP SEMANTIC VIEW IF EXISTS FPA_DEMO.FPA.FPA_SEMANTIC_VIEW;
DROP PROCEDURE IF EXISTS FPA_DEMO.FPA.RUN_SCENARIO(FLOAT, FLOAT, NUMBER, VARCHAR);
DROP PROCEDURE IF EXISTS FPA_DEMO.FPA.SUBMIT_REVIEW_PACKAGE(VARCHAR, VARCHAR);
DROP PROCEDURE IF EXISTS FPA_DEMO.FPA.APPROVE_REVIEW_PACKAGE(VARCHAR);
DROP STAGE IF EXISTS FPA_DEMO.FPA.AGENT_SKILLS;          -- agent skill (fpa-variance-review)
DROP STREAMLIT IF EXISTS FPA_DEMO.FPA.FPA_AGENT_COST_ESTIMATOR;
DROP STAGE IF EXISTS FPA_DEMO.FPA.APP_STAGE;
DROP PROCEDURE IF EXISTS FPA_DEMO.FPA.RUN_AGENT_LOAD_TEST(NUMBER, VARCHAR);
DROP VIEW IF EXISTS FPA_DEMO.FPA.V_RUN_COSTS;
DROP VIEW IF EXISTS FPA_DEMO.FPA.V_AGENT_QUESTION_COSTS;
DROP VIEW IF EXISTS FPA_DEMO.FPA.V_AGENT_TOOL_QUERIES;
DROP PROCEDURE IF EXISTS FPA_DEMO.FPA.START_COST_RUN(VARCHAR, VARCHAR);
DROP PROCEDURE IF EXISTS FPA_DEMO.FPA.END_COST_RUN(VARCHAR);
DROP TABLE IF EXISTS FPA_DEMO.FPA.COST_RUNS;
DROP VIEW IF EXISTS FPA_DEMO.FPA.V_COST_CALIBRATION;
DROP VIEW IF EXISTS FPA_DEMO.FPA.V_LOAD_TEST_COSTS;
DROP VIEW IF EXISTS FPA_DEMO.FPA.V_AGENT_REQUESTS;
DROP VIEW IF EXISTS FPA_DEMO.FPA.V_AGENT_REQUEST_COSTS;
DROP TABLE IF EXISTS FPA_DEMO.FPA.AGENT_LOAD_TEST_LOG;
DROP TABLE IF EXISTS FPA_DEMO.FPA.FACT_PL;
DROP TABLE IF EXISTS FPA_DEMO.FPA.FACT_FORECAST;
DROP TABLE IF EXISTS FPA_DEMO.FPA.DIM_ENTITY;
DROP TABLE IF EXISTS FPA_DEMO.FPA.DIM_PRODUCT;
DROP TABLE IF EXISTS FPA_DEMO.FPA.ASSUMPTION_DOCS;
DROP TABLE IF EXISTS FPA_DEMO.FPA.REVIEW_PACKAGE_LOG;
DROP TABLE IF EXISTS FPA_DEMO.FPA.NOTIFICATION_OUTBOX;
DROP DATABASE IF EXISTS FPA_DEMO;
DROP WAREHOUSE IF EXISTS FPA_DEMO_WH;
DROP WAREHOUSE IF EXISTS FPA_AGENT_WH;
DROP RESOURCE MONITOR IF EXISTS FPA_DEMO_RM;
DROP INTEGRATION IF EXISTS PYPI_ACCESS_INTEGRATION;   -- skip if other apps use it
DROP USER IF EXISTS FPA_DEMO_USER;
DROP ROLE IF EXISTS FPA_DEMO_ROLE;
