-- ============================================================================
-- Pipeline Cost Optimization Demo - Emergency Stop and Cleanup
--
-- Run Block 1 immediately when the demo ends. It suspends tasks and aborts
-- in-flight work while preserving the demo objects for another session.
-- Run Block 4 only when the demo is finished permanently.
-- ============================================================================

USE ROLE ACCOUNTADMIN;

-- ============================================================================
-- BLOCK 1 - EMERGENCY STOP
-- ============================================================================
ALTER TASK IF EXISTS PIPELINE_COST_DEMO.INGESTION.T_INGEST_MERGE_XS SUSPEND;
ALTER TASK IF EXISTS PIPELINE_COST_DEMO.INGESTION.T_INGEST_MERGE_S SUSPEND;
ALTER TASK IF EXISTS PIPELINE_COST_DEMO.INGESTION.T_REPORTING_REFRESH SUSPEND;
ALTER TASK IF EXISTS PIPELINE_COST_DEMO.INGESTION.T_VARIANT_ENRICHMENT SUSPEND;

ALTER WAREHOUSE IF EXISTS DEMO_INGEST_WH_XS ABORT ALL QUERIES;
ALTER WAREHOUSE IF EXISTS DEMO_INGEST_WH_S ABORT ALL QUERIES;
ALTER WAREHOUSE IF EXISTS DEMO_REPORTING_WH ABORT ALL QUERIES;

-- A warehouse already suspended returns an Invalid state error. That is
-- harmless: it means the warehouse is already parked.
ALTER WAREHOUSE IF EXISTS DEMO_INGEST_WH_XS SUSPEND;
ALTER WAREHOUSE IF EXISTS DEMO_INGEST_WH_S SUSPEND;
ALTER WAREHOUSE IF EXISTS DEMO_REPORTING_WH SUSPEND;

-- ============================================================================
-- BLOCK 2 - VERIFY THE STOP
-- ============================================================================
SHOW TASKS IN SCHEMA PIPELINE_COST_DEMO.INGESTION;
SHOW WAREHOUSES LIKE 'DEMO_%';

SELECT NAME, STATE, SCHEDULED_TIME, COMPLETED_TIME, ERROR_CODE,
       LEFT(ERROR_MESSAGE, 160) AS ERROR_MESSAGE
FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY(
    SCHEDULED_TIME_RANGE_START => DATEADD(hour, -1, CURRENT_TIMESTAMP()),
    RESULT_LIMIT => 200))
WHERE NAME IN (
    'T_INGEST_MERGE_XS',
    'T_INGEST_MERGE_S',
    'T_REPORTING_REFRESH',
    'T_VARIANT_ENRICHMENT'
)
ORDER BY SCHEDULED_TIME DESC;

-- ============================================================================
-- BLOCK 3 - OPTIONAL COST REVIEW
-- ============================================================================
SELECT WAREHOUSE_NAME,
       ROUND(SUM(CREDITS_USED_COMPUTE), 3) AS COMPUTE_CREDITS,
       ROUND(SUM(CREDITS_USED_CLOUD_SERVICES), 3) AS CLOUD_SERVICES_CREDITS,
       ROUND(SUM(CREDITS_USED), 3) AS TOTAL_CREDITS
FROM TABLE(INFORMATION_SCHEMA.WAREHOUSE_METERING_HISTORY(
    DATEADD(day, -2, CURRENT_TIMESTAMP())))
WHERE WAREHOUSE_NAME LIKE 'DEMO_%'
GROUP BY WAREHOUSE_NAME
ORDER BY TOTAL_CREDITS DESC;

-- ============================================================================
-- BLOCK 4 - FULL TEARDOWN
-- ============================================================================
DROP TASK IF EXISTS PIPELINE_COST_DEMO.INGESTION.T_INGEST_MERGE_XS;
DROP TASK IF EXISTS PIPELINE_COST_DEMO.INGESTION.T_INGEST_MERGE_S;
DROP TASK IF EXISTS PIPELINE_COST_DEMO.INGESTION.T_REPORTING_REFRESH;
DROP TASK IF EXISTS PIPELINE_COST_DEMO.INGESTION.T_VARIANT_ENRICHMENT;

ALTER WAREHOUSE IF EXISTS DEMO_INGEST_WH_XS UNSET RESOURCE_MONITOR;
ALTER WAREHOUSE IF EXISTS DEMO_INGEST_WH_S UNSET RESOURCE_MONITOR;
ALTER WAREHOUSE IF EXISTS DEMO_REPORTING_WH UNSET RESOURCE_MONITOR;
ALTER WAREHOUSE IF EXISTS DEMO_BUILD_WH UNSET RESOURCE_MONITOR;

DROP WAREHOUSE IF EXISTS DEMO_INGEST_WH_XS;
DROP WAREHOUSE IF EXISTS DEMO_INGEST_WH_S;
DROP WAREHOUSE IF EXISTS DEMO_REPORTING_WH;
DROP WAREHOUSE IF EXISTS DEMO_BUILD_WH;

DROP RESOURCE MONITOR IF EXISTS DEMO_COST_GUARD;
DROP DATABASE IF EXISTS PIPELINE_COST_DEMO;

-- Confirm the teardown.
SHOW WAREHOUSES LIKE 'DEMO_%';
SHOW DATABASES LIKE 'PIPELINE_COST_DEMO';
SHOW RESOURCE MONITORS LIKE 'DEMO_COST_GUARD';
